sudo: false

language: go

go:
- 1.11.x

addons:
  apt:
    packages:
    - docker-ce

before_install:
- mkdir -p $HOME/gopath/src/github.com/cellery-io
- mv ${TRAVIS_BUILD_DIR} $GOPATH/src/github.com/cellery-io/mesh-controller
- export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/cellery-io/mesh-controller
- cd $HOME/gopath/src/github.com/cellery-io/mesh-controller

# Only use the code in vendor/ :)
install: true

script:
- pwd
- env
- make build.controller
- docker --version
- make docker.controller
- docker --version
- go test -race -coverprofile=coverage.txt -covermode=atomic ./pkg/controller/service/resources/

after_success:
- bash <(curl -s https://codecov.io/bash)
