sudo: false

language: go

go:
- 1.12.x

addons:
  apt:
    packages:
    - docker-ce

env:
- GO111MODULE=on

# Put the source code into correct GOPATH in order to allow forked repos to build properly in travis
before_install:
- mkdir -p $HOME/gopath/src/github.com/cellery-io
- mv ${TRAVIS_BUILD_DIR} $GOPATH/src/github.com/cellery-io/mesh-controller
- export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/cellery-io/mesh-controller
- cd $HOME/gopath/src/github.com/cellery-io/mesh-controller

before_script:
- make tools

script:
- test -z "$(make code.format-check| tee /dev/stderr)"
- make verify-codegen
- make build.controller
- make docker.controller
- make test.controller
- git diff --exit-code

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make docker-push.controller
  on:
    branch: master
  skip_cleanup: true
